version: '3'

service:
  seed:
    build: database/
    depends_on:
      - 'database'

  database:
    image: mongo:latest

  reservations:
    build: .
    depends_on:
      - 'seed'
    ports:
      - '3008:3002'